### ISSUE TITLE
Recognition speed

### ISSUE THREAD

**Issue by INTKILOW** [watson-developer-cloud/android-sdk#65]
Why is recognition slow in China……About 4 seconds

**Comment by lpatino10** [comment]
Hi @INTKILOW. I'm sorry that the service is slower than you might like, but that is outside of the scope of this SDK. I'll be sure to ask the speech team about it to see if it's a known problem.

It is possible that there was some temporary slowdown, so I'd encourage you to try hitting the service again.

I'm going to go ahead and close this issue though, since it's a possible issue on the service side instead.

**Comment by INTKILOW** [comment]
Is there any difference between speech-android-sdk  and android-sdk,The service credentials do not have a username and password, only an apikey

**Comment by INTKILOW** [comment]
How to add microphone volume size callback
