### ISSUE TITLE
update example to include updated api key login

### ISSUE THREAD

**Issue by himuragaming** [watson-developer-cloud/android-sdk#70]
I first posted this over at [stackoverflow ](https://stackoverflow.com/questions/54433473/ibm-watson-speech-to-text)but I get no support there as to what the code would be for getting data from ibm watson over an api key. Please update the example to include use of the latest way to login. thanks

**Comment by lpatino10** [comment]
Hey @himuragaming. It looks like the repo you linked to in that issue was a deprecated speech library we used to have, but this is the correct one.

This library is built to work with the [Java SDK](https://github.com/watson-developer-cloud/java-sdk), so that's where you can find information on how to authenticate with your service. Specifically though, you'll want to look in [this section](https://github.com/watson-developer-cloud/java-sdk#iam).

To put everything here, if you have your API key in your resources, you can do the following:
```java
SpeechToText service = new SpeechToText();
IamOptions options = new IamOptions.Builder()
  .apiKey(R.string.stt_api_key) // this is your API key
  .build();
service.setIamCredentials(options);
```

You should now be able to make authenticated API calls using that `service` object.
