### ISSUE TITLE
Continuous Listening with android sdk

### ISSUE THREAD

**Issue by prokulit06** [watson-developer-cloud/android-sdk#75]
Is this equivalent in inActivityTimeout or it is different because I tried this .continues like in the demo but not defined in android sdk??? is .continues is not available in android sdk?

**Comment by lpatino10** [comment]
Hey @prokulit06. I'll need to update the example because the `continuous` parameter when using Speech to Text is actually deprecated, so it makes sense that it wouldn't work. We don't actually use it in the example, though.

Either way, the old behavior that would result from setting `continuous` to `true` is now the **default** behavior, so if that's what you were trying to do, you don't need to worry about it.

If you were trying to replicate the old `continuous = false` behavior, see [here](https://developer.ibm.com/answers/questions/379129/watson-speech-to-text-deprecation-of-continuous-pa/) for a workaround.
